#!/bin/bash
sudo pacman -Rdd intel-ucode
sudo pacman -S --noconfirm --needed nvidia-dkms-tkg nvidia-utils-tkg nvidia-settings-tkg opencl-nvidia-tkg lib32-nvidia-utils-tkg lib32-opencl-nvidia-tkg linux-tkg linux-tkg-headers && reboot
