#!/bin/bash
#!/bin/bash
#!/bin/bash
#set -e
##################################################################################################################
# Written to be used on 64 bits computers
# Author 	: 	DarkXero
# Website 	: 	http://xerolinux.github.io
##################################################################################################################
echo
tput setaf 4
echo "###############################################################################"
echo "#                    XeroLinux Flatpak Package Installer                      #"
echo "###############################################################################"
tput sgr0
echo
echo "#################################"
echo "      Install Yer Flatpaks       "
echo "#################################"
echo
flatpak install -y audacity gitahead rpi-imager jitsi-meet zoom filezilla bitwarden parsec warpinator PlexDesktop PlexHTPC stremio mpv vlc handbrake mkvtoolnix-gui filebot makemkv org.remmina.Remmina libreoffice openrgb firmware ferdium io.github.spacingbat3.webcord thunderbird org.gnome.Rhythmbox3 com.obsproject.Studio com.obsproject.Studio.Locale com.obsproject.Studio.Plugin.Gstreamer com.obsproject.Studio.Plugin.InputOverlay com.obsproject.Studio.Plugin.MoveTransition com.obsproject.Studio.Plugin.OBSVkCapture com.obsproject.Studio.Plugin.ScaleToSound com.obsproject.Studio.Plugin.SceneSwitcher com.obsproject.Studio.Plugin.TransitionTable com.obsproject.Studio.Plugin.WebSocket com.obsproject.Studio.Plugin.waveform
echo
echo "#################################"
echo "          Done! Exit Me          "
echo "#################################"
